version: "3.9"
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      interval: 2s
      timeout: 2s
      retries: 15

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
     - 9093:9093
    links:
     - zookeeper
    networks:
      - default
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 2s
      timeout: 2s
      retries: 15
    depends_on:
      - zookeeper
  
  schema-registry:
    platform: linux/amd64
    image: confluentinc/cp-schema-registry
    ports:
     - 8181:8181
     - 8081:8081
    environment:
     - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181
     - SCHEMA_REGISTRY_DEBUG=true
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
     - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092

    links:
     - zookeeper
    depends_on:
      - kafka

  connect:
    platform: linux/amd64
    build:
      context: debezium-jdbc-es
      args:
        JMX_AGENT_VERSION: 0.15.0
    ports:
     - 8083:8083
     - 1976:1976
    restart: on-failure:5
    # links:
    #  - kafka
    #  - citus

    environment:
      - BOOTSTRAP_SERVERS=kafka:9093
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - KAFKA_HEAP_OPTS= -Xmx4G -Xms4G
      - CONNECT_PLUGIN_PATH=/usr/share/confluent-hub-components,/data/connect-jars
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9093
      - CONNECT_GROUP_ID=1
      - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs_2
      - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets_2
      - CONNECT_STATUS_STORAGE_TOPIC=my_connect_statuses_2
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR=1
      - CONNECT_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONNECT_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - CONNECT_TRANSACTION_STATE_LOG_MIN_ISR=1
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect:8083
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=schema-registry:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=schema-registry:8081
    volumes:
      - $PWD/data:/data
