version: "3.9"
services:
  citus:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - 5432:5432
    volumes:
      - ./ads.csv:/data/ads.csv
      - ./campaigns.csv:/data/campaigns.csv
      - ./companies.csv:/data/companies.csv
    env_file:
      - .env

  sink_db:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - 5433:5432
    volumes:
      - ./ads.csv:/data/ads.csv
      - ./campaigns.csv:/data/campaigns.csv
      - ./companies.csv:/data/companies.csv
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - .env

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc-es
    ports:
     - 8083:8083
    links:
     - kafka
     - citus
     - sink_db
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

volumes:
    postgres: